version: '3'

services:
  monitoreodeservidoresback:
    platform: amd64
    container_name: monitoreo_de_servidores_back
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '3001:3001'
networks:
  default:
    external: true
    name: nginx-proxy-manager_default